# Generated by Django 3.2.6 on 2021-10-28 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 10, 28, 18, 24, 21, 25627, tzinfo=utc), upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
