# Generated by Django 3.2.6 on 2022-02-23 13:46

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220131_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[apps.users.models.username_validation], verbose_name='username'),
        ),
    ]
