# Generated by Django 3.2.6 on 2021-09-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='about me'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=32, verbose_name='sex'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='def_val', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='web_site',
            field=models.URLField(blank=True, null=True, verbose_name='web site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
    ]
