# Generated by Django 3.2.6 on 2022-02-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
