# Generated by Django 3.2.6 on 2022-02-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
