# Generated by Django 3.2.6 on 2022-02-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
