# Generated by Django 3.2.6 on 2021-12-11 22:10

import apps.catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20211210_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, validators=[apps.catalog.validators.validate_tag], verbose_name='Tag'),
        ),
    ]
