# Generated by Django 3.2.6 on 2021-12-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
