# Generated by Django 3.2.6 on 2021-12-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='text',
            field=models.CharField(max_length=255, verbose_name='replies'),
        ),
    ]
