# Generated by Django 3.2.6 on 2021-11-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments_on',
            new_name='comments_off',
        ),
    ]
