# Generated by Django 3.2.6 on 2021-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='description of post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments_off',
            field=models.BooleanField(default=False, verbose_name='is comments disabled?'),
        ),
    ]
