# Generated by Django 3.2.6 on 2021-12-12 19:47

import apps.catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_comment_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[apps.catalog.validators.validate_tag], verbose_name='Tag'),
        ),
    ]
