# Generated by Django 3.2.6 on 2021-12-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_commentreply_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
